### ISSUE TITLE
Feature Request: add a --with-ghc flag to sandbox creation

### ISSUE THREAD

**Issue by rpglover64** [abhinav/sandman#1]
I think almost all that's necessary on the cabal side is to create a cabal.config with a with-compiler field.

**Comment by abhinav** [comment]
This seems simple enough. Would the same version of GHC be used when mixing a managed sandbox into your project sandbox?

**Comment by abhinav** [comment]
Decided to go with the behavior where mixing in a sandbox means that you're also taking the same GHC version. The most recently mixed sandbox gets to set the version. No modifications are made if a sandbox didn't have the path explicitly set (using `--with-ghc`).
